[tool.poetry]
name = "smallgame"
version = "0.1.0"
description = ""
authors = ["Kate lin"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
pygame = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
